CREATE TABLE AUTH(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  LOGIN VARCHAR(255),
  HASH VARCHAR(64),
  SALT VARCHAR(64),
  NAME VARCHAR(255),
  CONSTRAINT UNQ_USER_LOGIN
    UNIQUE (LOGIN)
);

CREATE TABLE ROLES(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  AUTH_ID INT,
  ROLE VARCHAR(255),
  RESOURCE VARCHAR(255),
  CONSTRAINT FK_ROLES_AUTH_ID
    FOREIGN KEY (AUTH_ID)
    REFERENCES AUTH (ID)
);

CREATE TABLE ACCOUNTING(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ROLES_ID INT,
  START_DATE DATE,
  END_DATE DATE,
  VOLUME INT,
  CONSTRAINT FK_ACCOUNTING_ROLES_ID
    FOREIGN KEY (ROLES_ID)
    REFERENCES ROLES (ID)
);

CREATE INDEX IDX_AUTHORITY
  ON ROLES (AUTH_ID, ROLE);

  INSERT INTO AUTH(ID,NAME,LOGIN,HASH,SALT) VALUES
       (1, 'John Doe', 'jdoe',
       'cca635b25156988da32d2f77c44d67a',
       'saltsaltsalt'), -- sup3rpaZZ
       (2, 'Jane Row', 'jrow',
       'd3f1872ff3dd7e2cef9be2af9cf58fb',
       'supersalt'); -- Qweqrty12

INSERT INTO ROLES (ID,AUTH_ID,ROLE,RESOURCE) VALUES
       (1,1,'READ', 'a'),
       (2,1,'WRITE', 'a.b'),
       (3,2,'EXEC', 'a.b.c'),
       (4,1,'EXEC', 'a.bc');